/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Recess Design Tokens
        'twilight-navy': '#25385b',
        'periwinkle-sky': '#a2b0ff',
        'dusk-indigo': '#0a0a3a',
        'cobalt-pop': '#3252f4',
        'coral-blush': '#ff5a5a',
        'cloud-white': '#ffffff',
        'cream-linen': '#fffcef',
        'slate-mist': '#84849c',
        onyx: '#000000',

        // Recess Surface Tokens
        'recess-canvas': '#fffcef',
        'recess-card': '#ffffff',
        'recess-alt': '#fffcef',
        'recess-border': '#25385b',
        'recess-border-subtle': '#84849c',
        'recess-dark': '#0a0a3a',

        // Compatibility Mappings
        blurple: '#3252f4',
        'dark-blurple': '#25385b',
        'hover-blurple': '#a2b0ff',
        'spring-green': '#10b981',
        fuchsia: '#ff5a5a',
        'vivid-cerulean': '#3252f4',
        'ember-orange': '#ff5a5a',
        'ekko-red': '#ff5a5a',
        void: '#000000',
        snow: '#ffffff',
        'not-quite-black': '#25385b',
        'dark-charcoal': '#25385b',
        graphite: '#84849c',
        fog: '#84849c',
        greyple: '#84849c',
        'dim-grey': '#84849c',
        'off-white': '#fffcef',

        // Surface compatibility
        'cosmic-page': '#fffcef',
        'discord-deep': '#0a0a3a',
        'discord-card': '#ffffff',
        'discord-panel': '#fffcef',
        'discord-hover': '#f0f3ff',
        'discord-border': '#25385b',
        'discord-border-subtle': '#84849c',

        'sandy-desk': '#fffcef',
        'paper-white': '#ffffff',
        'cream-paper': '#fffcef',
        'soft-linen': '#f4f6ff',
        'pale-stone': '#e8edff',
        'deep-moss': '#25385b',
        'olive-char': '#25385b',
        'sage-gray': '#84849c',
        'ash-green': '#84849c',
        'faded-pewter': '#84849c',
        'warm-mist': '#84849c',
        'pure-black': '#000000',
        'signal-blue': '#3252f4',
        'amber-glow': '#3252f4',
        'dark-amber': '#25385b',
        'burnished-gold': '#a2b0ff',
        'marigold': '#ff5a5a',
        'flame-orange': '#ff5a5a',
        'moss-green': '#10b981',
      },
      fontFamily: {
        sans: ['DM Sans', 'Space Grotesk', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        runde: ['Space Grotesk', 'DM Sans', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        script: ['Caveat', 'Pacifico', 'cursive', 'sans-serif'],
        mono: ['IBM Plex Mono', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '8px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '20px',
        window: '12px',
        card: '8px',
        full: '9999px',
        pill: '9999px',
      },
      boxShadow: {
        none: 'none',
        recess: '0 2px 8px rgba(37, 56, 91, 0.08)',
        'recess-card': '0 4px 16px rgba(37, 56, 91, 0.06)',
        'recess-pop': '0 8px 24px rgba(37, 56, 91, 0.12)',
        discord: '0 2px 8px rgba(37, 56, 91, 0.08)',
        'discord-lg': '0 6px 18px rgba(37, 56, 91, 0.12)',
        'blurple-glow': '0 2px 8px rgba(50, 82, 244, 0.25)',
        'cerulean-glow': '0 2px 8px rgba(162, 176, 255, 0.35)',
        modal: '0 20px 45px rgba(10, 10, 58, 0.25)',
      },
      letterSpacing: {
        tightest: '-0.025em',
        subheading: '-0.475px',
        heading: '-0.525px',
        'heading-lg': '-0.6px',
        ginto: '-0.01em',
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'equalizer': 'equalizer 1.2s ease-in-out infinite alternate',
        'recess-float-slow': 'recessFloat 20s ease-in-out infinite alternate',
        'recess-float-reverse': 'recessFloatRev 25s ease-in-out infinite alternate',
        'recess-pulse-glow': 'recessPulse 15s ease-in-out infinite alternate',
      },
      keyframes: {
        equalizer: {
          '0%': { height: '15%' },
          '50%': { height: '100%' },
          '100%': { height: '40%' },
        },
        recessFloat: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '50%': { transform: 'translate(40px, -30px) scale(1.08)' },
          '100%': { transform: 'translate(-30px, 40px) scale(0.95)' },
        },
        recessFloatRev: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '50%': { transform: 'translate(-40px, 35px) scale(1.06)' },
          '100%': { transform: 'translate(30px, -35px) scale(0.96)' },
        },
        recessPulse: {
          '0%': { opacity: '0.45', transform: 'scale(0.98)' },
          '50%': { opacity: '0.75', transform: 'scale(1.08)' },
          '100%': { opacity: '0.45', transform: 'scale(0.98)' },
        },
      }
    },
  },
  plugins: [],
}
